chore(deps): bump io.milvus:milvus-sdk-java from 2.6.13 to 2.6.16 (#1024)
Bumps
[io.milvus:milvus-sdk-java](https://github.com/milvus-io/milvus-sdk-java)
from 2.6.13 to 2.6.16.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/milvus-io/milvus-sdk-java/releases">io.milvus:milvus-sdk-java's
releases</a>.</em></p>
<blockquote>
<h2>milvus-sdk-java-2.6.16</h2>
<p>Release date: 2026-03-19</p>
<p>Compatible with Milvus v2.6.x</p>
<h3>Feature</h3>
<ul>
<li>Add truncateCollection() interface for MilvusClientV2</li>
</ul>
<h3>Bug</h3>
<ul>
<li>Fix a potential risk of sending multiple HTTP requests to the global
cluster endpoint in a short time</li>
<li>Fix NoSuchMethodError on Java 8 for java.nio.ByteBuffer when
querying with a sparse vector field</li>
</ul>
<h2>milvus-sdk-java-2.6.15</h2>
<p>Release date: 2026-03-09</p>
<p>Compatible with Milvus v2.6.x</p>
<h3>Feature</h3>
<ul>
<li>Add client support for global cluster</li>
</ul>
<h3>Bug</h3>
<ul>
<li>Fix a bug that Struct field name is missed in the response of
describeCollection()</li>
</ul>
<h2>milvus-sdk-java-2.6.14</h2>
<p>Release date: 2026-02-12</p>
<p>Compatible with Milvus v2.6.x</p>
<h3>Feature</h3>
<ul>
<li>Support AISAQ index type</li>
<li>Support element_filter for struct field</li>
</ul>
<h3>Improvement</h3>
<ul>
<li>Change keepAliveTimeMs from 55s to 10s, keepAliveTimeoutMs from 20s
to 5s, and enable keepAliveWithoutCalls by default in both ConnectParam
(V1) and ConnectConfig (V2).</li>
</ul>
<h3>Bug</h3>
<ul>
<li>Fix a bug in ClientPool where the RPC channel was not properly
closed</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/milvus-io/milvus-sdk-java/blob/master/CHANGELOG.md">io.milvus:milvus-sdk-java's
changelog</a>.</em></p>
<blockquote>
<h2>milvus-sdk-java 2.6.16 (2026-03-19)</h2>
<h3>Feature</h3>
<ul>
<li>Add truncateCollection() interface for MilvusClientV2</li>
</ul>
<h3>Bug</h3>
<ul>
<li>Fix a potential risk to send multiple http requests to global
cluster endpoint in short time</li>
<li>Fix NoSuchMethodError on Java 8 for java.nio.ByteBuffer when
querying with sparse vector field</li>
</ul>
<h2>milvus-sdk-java 2.6.15 (2026-03-09)</h2>
<h3>Feature</h3>
<ul>
<li>Add client support for global cluster</li>
</ul>
<h3>Bug</h3>
<ul>
<li>Fix a bug that Struct field name is missed in response of
describeCollection()</li>
</ul>
<h2>milvus-sdk-java 2.6.14 (2026-02-12)</h2>
<h3>Feature</h3>
<ul>
<li>Support AISAQ index type</li>
<li>Support element_filter for struct field</li>
</ul>
<h3>Improvement</h3>
<ul>
<li>Change keepAliveTimeMs from 55s to 10s, keepAliveTimeoutMs from 20s
to 5s, and enable keepAliveWithoutCalls by default in both ConnectParam
(V1) and ConnectConfig (V2).</li>
</ul>
<h3>Bug</h3>
<ul>
<li>Fix a bug in ClientPool where the RPC channel was not properly
closed</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/0684e389e78ee69a1e223c721989f21f67d3e1e2"><code>0684e38</code></a>
Prepare for v2.6.16 (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1785">#1785</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/b41d82b148632025222e6c3f20bf73867a3c6e59"><code>b41d82b</code></a>
Fix NoSuchMethodError on Java 8 for java.nio.ByteBuffer (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1783">#1783</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/32de51e5f4e863d881a9e415d88710d554d980fc"><code>32de51e</code></a>
Add TruncateCollection API to Java SDK (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1781">#1781</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/33bc614cdc4dbbfdb05bb85146ac78100e560615"><code>33bc614</code></a>
Fix a potential risk to send multiple http requests to global cluster
endpoin...</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/9da85570cd644636e4cfe631abe803bad4089531"><code>9da8557</code></a>
Prepare for v2.6.15 (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1775">#1775</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/64e912c8573f7a723ac881152dfcad453bc96084"><code>64e912c</code></a>
Retry on REPLICATE_VIOLATION for global cluster region switch (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1774">#1774</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/b538584b9894a6d95abdaa3c16869a1b7aa2eceb"><code>b538584</code></a>
Add global cluster client support (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1772">#1772</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/08364a079749b8d27adf5034e028a0d917fa5db6"><code>08364a0</code></a>
Fix a bug of ClientUtils.getSDKVersion() returns empty string (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1771">#1771</a>)</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/310ac2ab0e6ba38379632ccdb0154259c0b92ca1"><code>310ac2a</code></a>
Add benchmark to compare performance difference between two sdk versions
(<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1">#1</a>...</li>
<li><a
href="https://github.com/milvus-io/milvus-sdk-java/commit/38953e63985ebb8c0f74e9be53150af6a09ec01e"><code>38953e6</code></a>
DescribeCollection fieldNames/vectorFieldNames for Array&lt;Struct&gt;
schema (<a
href="https://redirect.github.com/milvus-io/milvus-sdk-java/issues/1764">#1764</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/milvus-io/milvus-sdk-java/compare/v2.6.13...v2.6.16">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=io.milvus:milvus-sdk-java&package-manager=maven&previous-version=2.6.13&new-version=2.6.16)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>